// <auto-generated />
namespace _2011062879_TruongLeQuocDat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KHOITAOCACBANGCUAIDENTITY : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KHOITAOCACBANGCUAIDENTITY));
        
        string IMigrationMetadata.Id
        {
            get { return "202303141540193_KHOI TAO CAC BANG CUA IDENTITY"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
